### ISSUE TITLE
Time tracking section of home

### ISSUE THREAD

**Issue by Ankur982** [shabazalimalik69/afraid-shoe-4639#19]
- [x] reviews
- [x] email input section
- [x] store email to use 
- [x] add image
- [x] navigate to register page on clicking button
